Vagrant.configure("2") do |config|

  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.manage_guest = true
  config.hostmanager.ignore_private_ip = false
  config.hostmanager.include_offline = true

 # VM 1
  config.vm.define "vm1" do |vm1|
  vm1.vm.box = "ubuntu/trusty64"
  vm1.vm.hostname = "vm1"
  vm1.vm.network "private_network", ip: "192.168.33.10"

  vm1.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y git
      git config --global user.name "kolia131"
      git config --global user.email "kolya_ruin@mail.ru"
      git clone https://github.com/kolia131/OSMU
      cat OSMU/lab1/task2/123.txt
    SHELL
 end

 # VM 2
  config.vm.define "vm2" do |vm2|
  vm2.vm.box = "ubuntu/trusty64"
  vm2.vm.hostname = "vm2"
  vm2.vm.network "private_network", ip: "192.168.33.20"
 end
end
