Vagrant.configure("2") do |config|

  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.manage_guest = true
  config.hostmanager.ignore_private_ip = false
  config.hostmanager.include_offline = true

  puts "Введите количество ВМ (от 1 до 253): "
  vm_count = Integer(STDIN.gets)

  unless (1..253).include?(vm_count)
    puts "Неверное количество ВМ. Пожалуйста, введите число от 1 до 253."
    exit
  end

  config.vm.box = "ubuntu/trusty64"

  (1..vm_count).each do |i|
    config.vm.define "vm#{i}" do |vm|
      vm.vm.box = "ubuntu/trusty64"
      vm.vm.hostname = "vm#{i}"
      vm.vm.network "private_network", ip: "192.168.33.#{i + 10}"
      vm.vm.provider "virtualbox" do |vb|
        vb.name = "vm#{i}"
      end
    end
  end
end