Vagrant.configure("2") do |config|

  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.manage_guest = true
  config.hostmanager.ignore_private_ip = false
  config.hostmanager.include_offline = true

  config.vm.box = "ubuntu/trusty64"

  # Prompt for the number of VMs
  puts "Enter the number of VMs (1-253): "
  vm_count = Integer(STDIN.gets)

  unless (1..253).include?(vm_count)
    puts "Invalid number of VMs. Please enter a number between 1 and 253."
    exit
  end

  # Launch webserver VM
  config.vm.define "webserver" do |webserver|
    webserver.vm.hostname = "webserver"
    webserver.vm.network "private_network", ip: "192.168.33.10"
    webserver.vm.provider "virtualbox" do |vb|
      vb.name = "webserver"
    end
    # Provision webserver
    webserver.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y apache2
      sudo mkdir -p /var/www/html/
      echo "Welcome to the webserver!" | sudo tee /var/www/html/index.html
      sudo service apache2 restart
    SHELL
  end

  if vm_count > 1
    # Launch Tomcat VMs
    (1..(vm_count - 1)).each do |i|
     config.vm.define "tomcat#{i}" do |tomcat|
       tomcat.vm.hostname = "tomcat#{i}"
       tomcat.vm.network "private_network", ip: "192.168.33.#{i + 10}"
       tomcat.vm.provider "virtualbox" do |vb|
         vb.name = "tomcat#{i}"
       end
       # Provision Tomcat VMs
       tomcat.vm.provision "shell", inline: <<-SHELL
         sudo apt-get update
         sudo apt-get install -y openjdk-7-jdk
         wget --no-check-certificate https://archive.apache.org/dist/tomcat/tomcat-7/v7.0.107/bin/apache-tomcat-7.0.107.tar.gz
         tar -xf apache-tomcat-7.0.107.tar.gz
         sudo mkdir -p /opt/tomcat7
         sudo mv apache-tomcat-7.0.107/* /opt/tomcat7/
         sudo chown -R vagrant:vagrant /opt/tomcat7
         echo 'export CATALINA_HOME="/opt/tomcat7"' >> ~/.bashrc
         source ~/.bashrc
         sudo sed -i 's/Connector port="8080"/Connector port="8080" address="0.0.0.0"/' $CATALINA_HOME/conf/server.xml
         echo "Welcome to Tomcat on #{tomcat.vm.hostname}!" > $CATALINA_HOME/webapps/ROOT/index.html
         sudo $CATALINA_HOME/bin/startup.sh
       SHELL
     end
    end
end

  # Add VMs to /etc/hosts
  config.vm.provision "shell", inline: <<-SHELL
    sudo sh -c 'echo "192.168.33.10 webserver" >> /etc/hosts'
  SHELL

  if vm_count > 1
    (1..(vm_count - 1)).each do |i|
      config.vm.provision "shell", inline: <<-SHELL
        sudo sh -c 'echo "192.168.33.#{i + 10} tomcat#{i}" >> /etc/hosts'
      SHELL
    end
  end
end